"""
routers/registration.py
------------------------
Handles registering new animals and looking up their details.

Endpoints in this file:
- POST /register        -> register a new animal (Cow ID is auto-generated
                            by the backend -- the caller does NOT supply one)
- GET  /animal/{cow_id}  -> get details of a specific animal

Registration flow (per the project spec):
    photo -> ML embedding -> compare against existing embeddings
          -> if no duplicate -> create animal -> store embedding

The ML parts are MOCKED for now via services/mock_ml.py. The mock function
calls are isolated so a teammate can swap in the real ResNet50 model later
without touching this router.
"""

import os
import shutil
import sqlite3
from typing import Optional

from fastapi import APIRouter, HTTPException, UploadFile, File, Form

import db
import schemas
from services.mock_ml import generate_mock_embedding, mock_muzzle_verification

router = APIRouter(tags=["Registration"])

UPLOAD_DIR = "uploads/muzzle_photos"
os.makedirs(UPLOAD_DIR, exist_ok=True)


def _save_photo(cow_id: str, photo: UploadFile) -> str:
    """Save an uploaded photo to disk and return its path."""
    ext = os.path.splitext(photo.filename or "")[1] or ".jpg"
    dest_path = os.path.join(UPLOAD_DIR, f"{cow_id}{ext}")
    with open(dest_path, "wb") as f:
        shutil.copyfileobj(photo.file, f)
    return dest_path


@router.post("/register", response_model=schemas.RegisterResponse)
def register_animal(
    owner_name: str = Form(...),
    breed: Optional[str] = Form(None),
    age: Optional[int] = Form(None),
    policy_id: Optional[str] = Form(None),
    muzzle_photo: Optional[UploadFile] = File(None),
):
    """
    Register a new animal.

    The vet/surveyor does NOT provide a Cow ID -- one is generated by the
    backend (db.generate_cow_id()) as the very last step, right before the
    row is actually inserted. If the mock duplicate-photo check rejects
    the registration first, no id is generated/consumed at all, so ids
    stay gap-free under normal (non-concurrent) use.

    - If a muzzle photo is provided, a MOCK embedding is generated and
      compared against existing animals' mock embeddings before saving,
      to demonstrate where real duplicate-detection will plug in later.
      This mock comparison does NOT do any real biometric matching.
    """
    # Work out the candidate Cow ID up front so we have something to name
    # the uploaded photo file after and to run the mock duplicate check
    # against. Nothing is saved to the database yet at this point.
    cow_id = db.generate_cow_id()

    muzzle_photo_path = None
    if muzzle_photo is not None:
        muzzle_photo_path = _save_photo(cow_id, muzzle_photo)

        # ---- MOCK duplicate check (isolated so real ML can replace it later) ----
        # Uses a stricter threshold than /verify or /claim so a normal
        # registration isn't blocked by an unlucky random mock score.
        existing_cow_ids = [a["cow_id"] for a in db.get_all_animals()]
        mock_result = mock_muzzle_verification(
            muzzle_photo_path, existing_cow_ids, threshold=0.90
        )
        if mock_result["result_status"] == "MATCH":
            raise HTTPException(
                status_code=400,
                detail=(
                    "Possible duplicate detected by mock ML check: photo looks "
                    f"similar to existing animal '{mock_result['top_match_cow_id']}' "
                    f"(mock similarity {mock_result['similarity_score']}). "
                    "This is a MOCK result, not a real biometric match. "
                    "No Cow ID was assigned for this rejected attempt."
                ),
            )

    try:
        animal = db.register_animal(
            cow_id=cow_id,
            owner_name=owner_name,
            breed=breed,
            age=age,
            policy_id=policy_id,
            muzzle_photo_path=muzzle_photo_path,
        )
    except sqlite3.IntegrityError:
        # Extremely rare: two registrations computed the same next Cow ID
        # at almost the same instant (see generate_cow_id()'s docstring).
        # Simple MVP-appropriate handling: ask the caller to just retry --
        # the next call will compute a fresh id.
        raise HTTPException(
            status_code=409,
            detail=(
                f"Cow ID '{cow_id}' was just taken by a simultaneous "
                "registration. Please retry -- a new id will be generated."
            ),
        )

    if muzzle_photo_path is not None:
        embedding = generate_mock_embedding(muzzle_photo_path)
        db.add_embedding(cow_id, embedding)
        db.log_verification(
            cow_id=cow_id,
            verification_type="register",
            result_status="REGISTERED",
            photo_path=muzzle_photo_path,
        )

    return {
        "success": True,
        "cow_id": cow_id,
        "message": "Animal registered successfully",
        "animal": animal,
    }


@router.get("/animal/{cow_id}", response_model=schemas.AnimalResponse)
def get_animal_details(cow_id: str):
    """Fetch details of a single registered animal by cow_id."""
    animal = db.get_animal(cow_id)
    if animal is None:
        raise HTTPException(
            status_code=404,
            detail=f"Animal with cow_id '{cow_id}' not found.",
        )
    return animal

