"""
routers/verification.py
------------------------
Handles biometric verification requests.

IMPORTANT: The real ML model (ResNet50-based muzzle matching) is NOT
implemented yet. POST /verify currently returns a MOCK result generated by
services/mock_ml.mock_muzzle_verification(). When the real model is ready,
only that function's internals need to change -- this router does not.

Endpoints in this file:
- POST /verify                -> run a (mock) verification against all registered animals
- GET  /verification/{cow_id}  -> get verification history for one animal
"""

import os
import shutil
from typing import List

from fastapi import APIRouter, HTTPException, UploadFile, File

import db
import schemas
from services.mock_ml import mock_muzzle_verification

router = APIRouter(tags=["Verification"])

UPLOAD_DIR = "uploads/verify_photos"
os.makedirs(UPLOAD_DIR, exist_ok=True)


@router.post("/verify", response_model=schemas.VerificationResponse)
def verify_animal(photo: UploadFile = File(...)):
    """
    Run a (currently mocked) biometric verification.

    Real flow (future): embed the uploaded photo, compare it against every
    stored embedding, return the closest real match.

    Mock flow (now): pick a random registered animal as the "top match"
    with a plausible similarity score, purely so the API shape is final
    and the frontend/other teammates can build against it already.
    """
    ext = os.path.splitext(photo.filename or "")[1] or ".jpg"
    photo_path = os.path.join(UPLOAD_DIR, f"verify_{os.urandom(4).hex()}{ext}")
    with open(photo_path, "wb") as f:
        shutil.copyfileobj(photo.file, f)

    existing_cow_ids = [a["cow_id"] for a in db.get_all_animals()]
    mock_result = mock_muzzle_verification(photo_path, existing_cow_ids)

    # For a plain /verify call (not tied to a claimed identity), we log the
    # attempt against whichever cow_id the mock matched, if any.
    log_cow_id = mock_result["top_match_cow_id"] or "UNKNOWN"
    verification = db.log_verification(
        cow_id=log_cow_id,
        verification_type="verify",
        result_status=mock_result["result_status"],
        photo_path=photo_path,
        top_match_cow_id=mock_result["top_match_cow_id"],
        similarity_score=mock_result["similarity_score"],
    )

    return {
        "cow_id": log_cow_id,
        "top_match_cow_id": mock_result["top_match_cow_id"],
        "similarity_score": mock_result["similarity_score"],
        "result_status": mock_result["result_status"],
    }


@router.get("/verification/{cow_id}", response_model=List[schemas.VerificationHistoryItem])
def get_verification_history(cow_id: str):
    """Return verification history for an animal, newest first. 404 if the animal doesn't exist."""
    if db.get_animal(cow_id) is None:
        raise HTTPException(
            status_code=404,
            detail=f"Animal with cow_id '{cow_id}' not found.",
        )
    return db.get_verifications_for_animal(cow_id)
