[theme]
base = "light"
primaryColor = "#10b981"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
